# Importing Tensorflow 2.0

In [1]:
import tensorflow as tf

In [2]:
d0 = tf.ones((3,2,2))

In [3]:
print(d0.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [4]:
d1 = tf.zeros([2,2])
print(d1)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [5]:
d3 = tf.fill([3,3], 69)
print(d3)

tf.Tensor(
[[69 69 69]
 [69 69 69]
 [69 69 69]], shape=(3, 3), dtype=int32)


# Constant in tensorflow
## A constant is the simplest category of tensor
    
    * Not Trainable
    * can have any dimensions
    

In [6]:
from tensorflow import constant

In [7]:
a = constant(3, shape=[2,3])
print(a.numpy())

[[3 3 3]
 [3 3 3]]


In [8]:
b = constant([1,2,3,4] , shape = [2,2])
print(b)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


# Zeros_like 

In [9]:
d2 = tf.zeros_like(a)
print(d2)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


# Defining and initializing variables in tensorflow.

In [10]:
#Defining a variable
a0 = tf.Variable([1,2,3,45,8,165,5], dtype = tf.float32)

In [11]:
a1 = tf.Variable([22,4,5,77,88,2,6,74,4], dtype = tf.int16)

In [12]:
#Defining a constant
b = tf.constant(2 ,tf.float32)

In [13]:
#Computing the product
c0 = tf.multiply(a0, b)
c1 = a0*b

In [14]:
print(c1)

tf.Tensor([  2.   4.   6.  90.  16. 330.  10.], shape=(7,), dtype=float32)


# Basic Tensor Operations 
## Applying the addition operator

In [15]:
#Import constant and add from Tensorflow
from tensorflow import constant , add

In [16]:
# 0-Dimensional tensors
A0 = constant([1])
B0 = constant([2])

In [17]:
# 1-Dimensional tensors
A1 = constant([1,2])
B1 = constant([3,4])

In [18]:
#Define 2-Dimensional tensors
A2 = constant([[1,2], [3,4]])
B2 = constant([[4,5], [6,7]])

In [19]:
# Performing the addition with add()
C0 = add(A0,B0)
C1 = add(A1,B1)
C2 = add(A2,B2)


In [20]:
print("The value of C0 is {} \n C1 is {} \n C2 is {}".format(C0,C1,C2))

The value of C0 is [3] 
 C1 is [4 6] 
 C2 is [[ 5  7]
 [ 9 11]]


* The add() operation performs element-wise addition with tensors
* Element wise addition requires the tensors involved to be of the same shape.
* The add() operator is overloaded ,which means we can add two or more tensors using the "+" sign.

# Performing multiplication in tensorflow

* Element Wise Multiplication using the multiply() operation
* Matrix Multiplication using the matmul() operation
    * Must Satisfy - Number of columns of A must equal the number of rows of B.

## Applying the multiplication in tensorflow

In [21]:
from tensorflow import multiply , matmul, ones

In [22]:
#Define tensors
A0 = ones(1)
A31 = ones([3,1])
A34 = ones([3,4])
A43 = ones([4,3])


* Here the valid matmul() is matmul(A43 , A34) , we cannot perform matmul with A31 .Figure out why ? 

# Summing over dimensions of a tensor

## Using the reduce_sum() operator

* The reduce_sum() operator sums over the dimensions of a tensor
    * reduce_sum(A) sums over all dimensions of A.
    * reduce_sum(A,i) usms over dimension i.

In [23]:
from tensorflow import reduce_sum

#Define a tensor of 2x3x4
A = constant(5, shape=[2,3,4])
print(A)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(2, 3, 4), dtype=int32)


In [24]:
B = reduce_sum(A)
print(B)

tf.Tensor(120, shape=(), dtype=int32)


In [25]:
B1 = reduce_sum(A,0)
B1

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int32)>

In [26]:
B2 = reduce_sum(A,1)
B2

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[15, 15, 15, 15],
       [15, 15, 15, 15]], dtype=int32)>

# Advance Tensor Operations
## Operations and their functions
* gradient() --> Computes the slope of a function at a point
* reshape() --> reshapes a tensor(100x1 to 10x10)
* random() --> Populates a tensor with randomly drawn values

# Finding the optimum.
* in many problems , we will want to find the optimum of a function be it
    
    * Minimum :- Lowest value of a loss function.
    
    * Maxima :- Largest value of a objective function.


* We can do this using the gradient() operation
    * Optimum: find a point where gradient = 0
    
    * Minimum : change in gradient > 0
    
    * Maximum : change in gradient < 0
    

# Gradients in Tensorflow

In [27]:
import tensorflow as tf

x = tf.Variable(-1.0)

In [28]:
# Define y within instance of gradientTape
with tf.GradientTape() as tape:
    tape.watch(x)
    y = tf.multiply(x, x)

In [29]:
# Gradient of y at x
g = tape.gradient(y ,x)
print(g.numpy())

-2.0


# Image as tensors

## Reshaping a grayscale image

In [30]:
# Generate grayscale image 
gray  = tf.random.uniform([2,2], maxval = 255, dtype = 'int32')     #Populates a 2x2 matrix with integers from the range(0-255)

In [31]:
# Reshape grayscale image
gray  = tf.reshape(gray, [2*2, 1])

## Reshaping a color image

In [32]:
#Generate color image
color = tf.random.uniform([2,2,3], maxval=255, dtype='int32')

In [33]:
#Reshaping the image
color = tf.reshape(color, [2*2, 3])